"""remove platform user foreign keys

Revision ID: 60b4da6050fa
Revises: bb186e8078a9
Create Date: 2026-05-16 08:17:29.598746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b4da6050fa'
down_revision = 'bb186e8078a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medical_records_doctor_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('medical_records_doctor_id_fkey'), 'medical_records', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###