"""remove cross db user foreign keys

Revision ID: bb186e8078a9
Revises: 
Create Date: 2026-05-16 08:10:24.877028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb186e8078a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_access_audit_log')
    op.drop_constraint(op.f('admissions_doctor_id_fkey'), 'admissions', type_='foreignkey')
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('appointments_created_by_user_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('discharge_summaries_doctor_id_fkey'), 'discharge_summaries', type_='foreignkey')
    op.drop_constraint(op.f('patient_documents_uploaded_by_fkey'), 'patient_documents', type_='foreignkey')
    op.drop_index(op.f('ix_patient_profiles_hospital_patient_id'), table_name='patient_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patient_profiles_hospital_patient_id'), 'patient_profiles', ['hospital_id', 'patient_id'], unique=False)
    op.create_foreign_key(op.f('patient_documents_uploaded_by_fkey'), 'patient_documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('discharge_summaries_doctor_id_fkey'), 'discharge_summaries', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('appointments_created_by_user_fkey'), 'appointments', 'users', ['created_by_user'], ['id'])
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(op.f('admissions_doctor_id_fkey'), 'admissions', 'users', ['doctor_id'], ['id'])
    op.create_table('clinical_access_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accessed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clinical_access_audit_log_pkey'))
    )
    # ### end Alembic commands ###